---
nav:

# Project Information
site_name: My Site
site_url: ""
site_description: Description
site_author: Mihai Criveti

# Repository Information
repo_name: 'kubetalks/PyLadies-Dublin-Documentation-as-Code-with-mkdocs-and-pandoc'
repo_url: 'https://github.com/kubetalks/PyLadies-Dublin-Documentation-as-Code-with-mkdocs-and-pandoc'
edit_uri: 'edit/master/docs'
docs_dir: 'docs'
site_dir: 'site'
remote_branch: 'gh-pages'
remote_name: 'origin'

# Server info
dev_addr: '127.0.0.1:8000'

# Copyright
copyright: <a href="/about/">Mihai Criveti</a>.

# Theme
theme:
  name: material
  custom_dir: theme
  logo: 'logo.png'
  favicon: 'logo.png'
  palette:
    primary: 'black'
    accent: 'red'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'
  features:
    - tabs

# Extra stylesheet
extra_css:
  - 'extra-uml.css'
  - 'pdf.css'
  - 'mermaid.css'

extra_javascript:
  - 'extra-uml.js'
  - 'raphael.min.js'
  - 'underscore-min.js'
  - 'sequence-diagram-min.js'
  - 'flowchart.min.js'
  - 'mermaid.min.js'

# Plugins
plugins:
  - search
  - table-reader
#  - enumerate-headings
  - git-revision-date-localized
  - git-authors
  - minify:
      minify_html: true
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
      combined: false
  - awesome-pages:
      filename: .pages
      collapse_single_pages: false
      strict: false

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/crivetimihai

# Markdown extensions
markdown_extensions:
  - markdown_blockdiag:
      format: svg
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: "\U0001F517"
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - pymdownx.critic:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.highlight:
      css_class: codehilite
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
        custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      provider: 'github'
      repo_url_shortener: true
      repo_url_shorthand: false
      social_url_shorthand: true
      user: crivetimihai
      repo: kutetalks/mkdocs
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
